services:
  - type: web
    name: entrepreneur-hub
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgresql
          name: divineconnectionstreasure
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
